"""added metadata columns

Revision ID: a3b88f155c18
Revises: 86ff2b3bc36b
Create Date: 2025-08-08 10:46:29.004828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b88f155c18'
down_revision: Union[str, Sequence[str], None] = '86ff2b3bc36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('extention', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'extention')
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
