"""change_column_names

Revision ID: f926b988c9b1
Revises: a3b88f155c18
Create Date: 2025-08-08 11:43:58.485467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f926b988c9b1'
down_revision: Union[str, Sequence[str], None] = 'a3b88f155c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_name', sa.String(length=250), nullable=False))
    op.add_column('files', sa.Column('extension', sa.String(), nullable=False))
    op.drop_column('files', 'extention')
    op.drop_column('files', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('extention', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'extension')
    op.drop_column('files', 'file_name')
    # ### end Alembic commands ###
